stages:
  - lint
  - test
  - base
  - build
  - deploy

lint:
  image: gitlab.cloudcix.com:5005/utils/ci/lint
  stage: lint
  script:
    - flake8
  except:
    - master
    - stable

build_base:
  stage: base
  tags:
    - docker-build
  before_script:
    - echo "$GITLAB_KEY" > id_rsa
  script:
    - docker build -f deployment/dockerfiles/base.Dockerfile -t gitlab.cloudcix.com:5005/cloudcix/robot/base:latest --no-cache .
    - docker push gitlab.cloudcix.com:5005/cloudcix/robot/base:latest
  after_script:
    - docker system prune -f
  only:
    - master

build_alpha:
  stage: build
  tags:
    - docker-build
  script:
    - docker build -f deployment/dockerfiles/alpha.Dockerfile -t gitlab.cloudcix.com:5005/cloudcix/robot/alpha:latest --no-cache .
    - docker push gitlab.cloudcix.com:5005/cloudcix/robot/alpha:latest
  only:
  - master

deploy_alpha:
  image: gitlab.cloudcix.com:5005/cloudcix/deployment/image
  before_script:
    - cp ~/.ssh/application_framework/stage_key ~/.ssh/id_rsa
    - cp ~/.ssh/application_framework/stage_key.pub ~/.ssh/id_rsa.pub
  environment: staging
  stage: deploy
  script:
    - ansible-playbook -i deployment/hosts deployment/playbook.yml
  only:
    - master

build_toronto01:
  stage: build
  tags:
  - docker-build
  script:
  - docker build -f deployment/dockerfiles/toronto01.Dockerfile -t gitlab.cloudcix.com:5005/cloudcix/robot/toronto01:latest --no-cache .
  - docker push gitlab.cloudcix.com:5005/cloudcix/robot/toronto01:latest
  only:
  - stable

build_gov_cork:
  stage: build
  tags:
  - docker-build
  script:
  - docker build -f deployment/dockerfiles/gov_cork.Dockerfile -t gitlab.cloudcix.com:5005/cloudcix/robot/gov_cork:latest --no-cache .
  - docker push gitlab.cloudcix.com:5005/cloudcix/robot/gov_cork:latest
  only:
  - stable

deploy_production:
  image: gitlab.cloudcix.com:5005/cloudcix/deployment/image
  before_script:
    - cp ~/.ssh/application_framework/live_key ~/.ssh/id_rsa
    - cp ~/.ssh/application_framework/live_key.pub ~/.ssh/id_rsa.pub
  environment: production
  stage: deploy
  script:
    # Deploy all the production stuff
    # Toronto
    - ansible-playbook -i deployment/hosts deployment/playbook.yml --extra-vars="deployment_host=toronto01"
    # GovCork
    - ansible-playbook -i deployment/hosts deployment/playbook.yml --extra-vars="deployment_host=gov_cork"
  only:
    - stable
