stages:
- lint
- test
- docker-base
- publish
- docker
- deploy


lint:
    image: cloudcix/lint:latest
    stage: lint
    script:
    - flake8
    except:
    - master
    - stable

mypy:
    image: python:3.7
    stage: lint
    script:
    - pip3 install 'mypy<0.800'
    - mypy --ignore-missing-imports builders dispatchers metrics quiescers restarters scrubbers tasks updaters celery_app.py cloudcix_token.py email_notifier.py robot.py state.py utils.py
    except:
    - master
    - stable

###############################################################################
#                         Base Containers                                     #
###############################################################################
opensource_base:
    stage: docker-base
    image: gitlab/dind
    services:
    - docker:dind
    tags:
    - docker-build
    script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -f deployment/docker/opensource/base.Dockerfile -t gitlab.cloudcix.com:5005/cloudcix/robot/opensource-base --no-cache .
    - docker push gitlab.cloudcix.com:5005/cloudcix/robot/opensource-base
    only:
    - stable
    except:
    - tags


# Will be deployed to docker hub for our use in our Devtest Region POD
devtest_base:
    stage: docker-base
    image: gitlab/dind
    services:
    - docker:dind
    tags:
    - docker-build
    script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -f deployment/docker/opensource/base.Dockerfile -t gitlab.cloudcix.com:5005/cloudcix/robot/devtest --no-cache .
    - docker push gitlab.cloudcix.com:5005/cloudcix/robot/devtest
    when: manual
    except:
    - stable

stable_base:
    stage: docker-base
    image: gitlab/dind
    services:
    - docker:dind
    tags:
    - docker-build
    before_script:
    - echo "$GITLAB_KEY" > id_rsa
    script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -f deployment/docker/stable/base.Dockerfile -t gitlab.cloudcix.com:5005/cloudcix/robot/stable-base --no-cache .
    - docker push gitlab.cloudcix.com:5005/cloudcix/robot/stable-base
    only:
    - stable
    except:
    - tags

###############################################################################
#                         Github and Dockerhub Deploy                         #
###############################################################################
deploy_github:
    image: gitlab/dind
    services:
    - docker:dind
    before_script:
    - cp ~/.ssh/application_framework/live_key ~/.ssh/id_rsa
    - cp ~/.ssh/application_framework/live_key.pub ~/.ssh/id_rsa.pub
    stage: publish
    script:
    - /bin/bash deployment/github_deploy.sh
    when: manual
    only:
    - stable

opersource_dockerhub:
    stage: publish
    image: gitlab/dind
    services:
    - docker:dind
    tags:
    - docker-build
    script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - ./deployment/docker/publish/opensource.sh
    when: manual
    only:
    - stable
    except:
    - tags

devtest_dockerhub:
    stage: publish
    image: gitlab/dind
    services:
    - docker:dind
    tags:
    - docker-build
    before_script:
    - mkdir -p ~/.ssh
    - touch ~/.ssh/known_hosts
    - cd ~/.ssh
    - echo "${RUNNER_SSH_KEY}" > id_rsa
    - chmod 0400 id_rsa
    - ssh-keyscan -t rsa gitlab.cloudcix.com >> ~/.ssh/known_hosts
    script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - ./deployment/docker/publish/devtest.sh
    when: manual
    except:
    - stable

sast:
    stage: test
    
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/SAST-IaC.latest.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
