stages:
    - lint
    - deploy

lint:
    image: python:latest
    stage: lint
    before_script:
        - pip3 install flake8
    script: 
        - flake8 --exclude fabfile.py --ignore E402, __init.py__

deploy_staging:
    image: gitlab.cloudcix.com:5005/cloudcix/deployment/image
    before_script:
        - cp ~/.ssh/application_framework/stage_key ~/.ssh/id_rsa
        - cp ~/.ssh/application_framework/stage_key.pub ~/.ssh/id_rsa.pub
    environment: staging
    stage: deploy
    script:
        - ansible-playbook -v -i deployment/hosts deployment/deploy_stage.yml
    only: ["master"]
