stages:
    - lint
    - build
    - deploy

lint:
    image: gitlab.cloudcix.com:5005/utils/ci/lint
    stage: lint
    script:
        - flake8

build-alpha:
    stage: build
    tags:
        - docker-build
    script:
        - docker build -t gitlab.cloudcix.com:5005/cloudcix/robot:latest --no-cache .
        - docker push gitlab.cloudcix.com:5005/cloudcix/robot:latest
    after_script:
        - docker system prune -f

deploy_staging:
    image: gitlab.cloudcix.com:5005/cloudcix/deployment/image
    before_script:
        - cp ~/.ssh/application_framework/stage_key ~/.ssh/id_rsa
        - cp ~/.ssh/application_framework/stage_key.pub ~/.ssh/id_rsa.pub
    environment: staging
    stage: deploy
    script:
        - ansible-playbook -i deployment/hosts deployment/playbook.yml
    only: ["master"]
