---
- hosts: staging
  remote_user: administrator
  tasks:
    - name: Deploy Robot to Alpha Region for staging
      shell:
        - cd /home/administrator
        - git fetch origin
        - git reset --hard origin/master
        - pip install -U -r requirements.txt


