all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    staging:
      hosts:
        alpha:
          ansible_host: "2a02:2078:3::3"
      vars:
        env: alpha
        ansible_become_pass: J1t3nd3r1sKw3l
    production:
      hosts:
        # gov_cork:
        #   ansible_host: "10.13.1.3"
        #   env: gov_cork
        #   ansible_become_pass: c1xacc355

        #cork01:
        #  ansible_host: "2a02:2078:4::3"
        #  env: cork01
        #  ansible_become_pass: C1xacc355
        #nti-cork01:
        #  ansible_host: "2a02:2078:8::3"
        #  env: nti-cork01
        #  ansible_become_pass: C1xacc355
        #netsoc-cork01:
        #  ansible_host: "2a02:2078:9::3"
        #  env: netsoc-cork01
        #  ansible_become_pass: C1xacc355

        vodafone-cork01:
          ansible_host: "2a02:2078:11::3"
          env: vodafone-cork01
          ansible_become_pass: C1xacc355
