all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    staging:
      hosts:
        alpha:
          ansible_host: "2a02:2078:3::3"
      vars:
        env: alpha
        ansible_become_pass: J1t3nd3r1sKw3l
    production:
      hosts:
        # toronto01:
        #   ansible_host: "2a02:2078:5::3"
        #   env: toronto01
        #   ansible_become_pass: C1xacc355
        # gov_cork:
        #   ansible_host: "10.13.1.3"
        #   env: gov_cork
        #   ansible_become_pass: c1xacc355
        cork01:
          ansible_host: "2a02:2078:4::3"
          env: cork01
          ansible_become_pass: C1xacc355
