---
- hosts: "{{ deployment_host | default('staging') }}"
  vars:
    robot_dir: "/home/administrator/robot"
  remote_user: administrator
  tasks:
    - name: Check if Robot is already running
      shell: ps -ef | grep robot.py | grep -v grep
      register: is_running
      ignore_errors: yes

    - name: Start initial robot process if Robot isn't already running
      shell: CLOUDCIX_SETTINGS_MODULE=settings ROBOT_ENV=alpha python3 robot.py
      args:
        chdir: "{{ robot_dir }}"
      async: 100
      poll: 0
      when: is_running.rc == 1

    - name: "Deploy Robot to {{ env }} environment"
      git:
        repo: "git@gitlab.cloudcix.com:CloudCIX/Robot.git"
        dest: "{{ robot_dir }}"
        update: yes
        clone: no
        version: "{{ branch }}"

    - name: "Deploy {{ env }} settings"
      file:
        src: "{{ robot_dir }}/deployment/settings/{{ env }}_settings.py"
        dest: "{{ robot_dir }}/settings.py"
        state: link

    - name: Update requirements
      shell: pip3 install -U -r deployment/requirements.txt
      args:
        chdir: "{{ robot_dir }}"