---
- hosts: "{{ deployment_host | default('staging') }}"
  remote_user: administrator
  tasks:
    - name: Gracefully shut down last container
      docker_container:
        name: "robot-{{ env }}"
        state: stopped
        stop_timeout: 300
    - name: Deploy latest Robot image for {{ env }} region
      docker_container:
        - name: "robot-{{ env }}"
          image: "gitlab.cloudcix.com:5005/cloudcix/robot:latest"
          state: started
          restart-policy: unless-stopped
          pull: true
          network_mode: host
          env:
            ROBOT_ENV: "{{ env }}"

